runtime: nodejs
api_version: '1.0'
env: flexible
threadsafe: true
instance_class: B1
  #what is it: https://cloud.google.com/appengine/docs/flexible/python/reference/app-yaml#resource-settings
  #what are the costs? The CPU costs were very high (50 euros for almost no visitors), also a bit memory consumption on server. Other costs: https://cloud.google.com/appengine/pricing
handlers:
  - url: /stylesheets/(.*)
    application_readable: false
    static_files: stylesheets/\1
    require_matching_file: false
    upload: stylesheets/.*
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: '301'
env_variables:
  BUCKET_NAME: portfolio-gcs-bucket
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
network: {}
liveness_check:
  initial_delay_sec: 300
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2
readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300